// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/30/2026, 11:57:43 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/pedro/projects/architect-showcase/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/pedro/projects/architect-showcase/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/pedro/projects/architect-showcase/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/pedro/projects/architect-showcase/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/pedro/projects/architect-showcase/plugins/**/*.{js,ts,mjs}","/home/pedro/projects/architect-showcase/composables/**/*.{js,ts,mjs}","/home/pedro/projects/architect-showcase/utils/**/*.{js,ts,mjs}","/home/pedro/projects/architect-showcase/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/pedro/projects/architect-showcase/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/pedro/projects/architect-showcase/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/pedro/projects/architect-showcase/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;